index:
    path: /
    defaults:  { _controller: ContextService\Server\Controller\AppController::indexAction }
test:
    pattern: /test
    defaults:  { _controller: ContextService\Server\Controller\AppController::testAction }
fetch_page:
    pattern: /fetchpage/{account}/{pagename}/{actionname}
    defaults:  { _controller: ContextService\Server\Controller\AppController::fetchPageAction }
