index:
    path: /
    defaults:  { _controller: ContextService\Server\Controller\AppController::indexAction }
test:
    pattern: /demo
    defaults:  { _controller: ContextService\Server\Controller\AppController::testAction }
fetch_page:
    pattern: /api/v1/index/{account}/{contextid}
    defaults:  { _controller: ContextService\Server\Controller\AppController::fetchIndexAction }
