index:
    path: /
    defaults:  { _controller: ContextService\Server\Controller\AppController::indexAction }
demo:
    pattern: /demo
    defaults:  { _controller: ContextService\Server\Controller\AppController::demoAction }
get_index:
    pattern: /api/v1/index/{account}/{contextid}
    defaults:  { _controller: ContextService\Server\Controller\AppController::getIndexAction }
